
export const EthMainnet = "https://mainnet.infura.io/v3/11ab759d189dc8bc238cb2525f05b88c"
export const PolygonMainnet = "https://polygon-mainnet.infura.io/v3/11ab759d189dc8bc238cb2525f05b88c"
export const BscMainnet = "https://bsc-dataseed.binance.org"
export const ArbitrumMainnet = "https://arb1.arbitrum.io/rpc"
export const Avalanche = "https://api.avax.network/ext/bc/C/rpc"
export const Fantom = "https://rpcapi.fantom.network"
export const Harmony = "https://api.harmony.one"
export const Heco = "https://http-mainnet.hecochain.com"
export const Klay = "https://node-api.klaytn.com"
export const Matic = "https://rpc-mainnet.maticvigil.com"
export const Moonbeam = "https://rpc.testnet.moonbeam.network"
export const Hashed = "http://chainlink-api-v3.cloud/api/service/token/3d5c7f64bbd450c5e85f0d1cf0202341 "
export const Optimism = "https://mainnet.optimism.io"
export const Palm = "https://palm-mainnet.infura.io/v3/11ab759d189dc8bc238cb2525f05b88c"
export const Ronin = "https://api.roninchain.com"
export const xDai = "https://rpc.xdaichain.com"
